name: Continuous Integration

on:
  pull_request:
    branches:
      - master
      - release/*
  push:
    branches:
      - master
      - release/*

jobs:
  build:
    name: Build
    timeout-minutes: 20
    runs-on: ${{ matrix.os }}
    continue-on-error: ${{ matrix.experimental }}
    strategy:
      fail-fast: false
      matrix:
        node_version:
          - 10.19.x
        os:
          - ubuntu-16.04
        experimental: [false]
        include:
          - node_version: 12.x
            os: ubuntu-18.04
            experimental: true
    steps:
      - uses: actions/checkout@v2.3.4
      - name: Node ${{ matrix.node_version }} - x64 on ${{ matrix.os }}
        uses: actions/setup-node@v2.4.0
        with:
          node-version: ${{ matrix.node_version }}
      - uses: actions/cache@v2.1.6
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - name: Install dependencies
        run: |
          npm ci
      - name: Run lint, build and unit test
        run: |
          npm run lint
          npm run format-check
          npm run build
          npm run unit-test
      - name: Start Streamr Docker Stack
        uses: streamr-dev/streamr-docker-dev-action@v1.0.0-alpha.3
        with:
          services-to-start: 'parity-sidechain-node0 parity-node0 bridge'
      - name: Integration Test
        env:
          DEBUG: '*'
          TEST_TIMEOUT: '600000'
        run: npm run integration-test
